### ISSUE TITLE
Issue/Help with "CSPM API"

### ISSUE THREAD

**Issue by SinceRonny** [PaloAltoNetworks/pan.dev#336]
## Documentation link
who knows what CSPM stands for? you should add at least put the full name once in this page

**Comment by jrdevore** [comment]
Hi @SinceRonny - Cloud Security Posture Management (CSPM) is displayed in  two locations on the pan.dev page you are referencing.

![image](https://github.com/PaloAltoNetworks/pan.dev/assets/3386501/b6edc514-c9f0-49e9-b185-382b83a1c4f9)

**Comment by jrdevore** [comment]
Addressed in #640
