### ISSUE TITLE
Issue/Help with "List Account Groups"

### ISSUE THREAD

**Issue by kleops9** [PaloAltoNetworks/pan.dev#503]
## Documentation link

[https://pan.dev/prisma-cloud/api/cspm/get-account-groups/](https://pan.dev/prisma-cloud/api/cspm/get-account-groups/)

## Describe the problem

typo/inaccuracy
The response schema differs from the example given

## Suggested fix

Update schema and/or example to be consistent

**Comment by AbiMano4688** [comment]
I do not see any inconsistencies or typos between schema and the example. Therefore, marking it closed.
