### ISSUE TITLE
Issue/Help with "pan.dev links to github and terraform registry"

### ISSUE THREAD

**Issue by sokupski** [PaloAltoNetworks/pan.dev#511]
## Documentation link

https://pan.dev/terraform/docs/swfw/aws/vmseries/modules/

## Describe the problem

Bad URL to the GitHub and Terraform Registry for every module I tested. I received at least 8 "404 - page not found" errors. I did not find any links that were correct.

**Comment by jamesholland-uk** [comment]
Issue to be fixed under https://github.com/PaloAltoNetworks/automation-metadata-collector/issues/9
