### ISSUE TITLE
Enum Value List not Displayed in pan.dev

### ISSUE THREAD

**Issue by AbiMano4688** [PaloAltoNetworks/pan.dev#587]
## Describe the bug

The enum values are available in the spec file but it is not displayed in pan.dev.

In the following endpoint, the enum values for the parameter filters->name is not displayed. However, the enum value is displayed for timerange->value->units.
- Get Mean Resolution Time
- Get Alerts Count By Resolution Reason

**Preview links:**

-  https://pan-dev-f1b58--pr583-xdni5mpc.web.app/prisma-cloud/api/cspm/value-widgets-alert-metrics-resolution-reason/
-  https://pan-dev-f1b58--pr583-xdni5mpc.web.app/prisma-cloud/api/cspm/value-widgets-alert-metrics/

**pan.dev links:** 

- https://pan.dev/prisma-cloud/api/cspm/value-widgets-alert-metrics-resolution-reason/
- https://pan.dev/prisma-cloud/api/cspm/value-widgets-alert-metrics/

**Spec file:** https://github.com/PaloAltoNetworks/pan.dev/blob/master/openapi-specs/cspm/CommandCenterMicroService.json

**PS:** The endpoint will be available on the live site from Jan 26th.
<img width="650" alt="image" src="https://github.com/PaloAltoNetworks/pan.dev/assets/62597279/96200e85-29fc-4df0-9c3a-57fda026b7b2">

**Comment by AbiMano4688** [comment]
cc: @manukumar6

**Comment by sserrata** [comment]
Hi @AbiMano4688, sorry for delay on getting this fix ready. When you have time can you review https://github.com/PaloAltoNetworks/pan.dev/pull/636 to see if the issue is resolved?

Direct link to preview: https://pan-dev-f1b58--pr636-q95d66gh.web.app/prisma-cloud/api/cspm/value-widgets-alert-metrics-resolution-reason/

**Comment by AbiMano4688** [comment]
Thanks @sserrata for fixing this issue.
