### ISSUE TITLE
Remove Empty "Request" Heading for GET Methods

### ISSUE THREAD

**Issue by AbiMano4688** [PaloAltoNetworks/pan.dev#589]
The Request heading appears even for the GET methods which do not have path or query parameters.

For example:
<img width="944" alt="image" src="https://github.com/PaloAltoNetworks/pan.dev/assets/62597279/3ddde1b9-9603-44c8-9240-6f264ffedfe3">
<img width="941" alt="image" src="https://github.com/PaloAltoNetworks/pan.dev/assets/62597279/f933caaa-de3a-4dfb-8b52-93f07796f3bc">

**Comment by AbiMano4688** [comment]
cc: @manukumar6

**Comment by sserrata** [comment]
Hi @AbiMano4688, this should also be resolved in https://github.com/PaloAltoNetworks/pan.dev/pull/636 preview
