### ISSUE TITLE
Issue/Help with "Add Policy" - Bad format on example JSON payload

### ISSUE THREAD

**Issue by ytimyno** [PaloAltoNetworks/pan.dev#601]
## Documentation link

https://pan.dev/prisma-cloud/api/cspm/add-policy/
Under "The JSON below is an example of the request body parameters you need to add a custom build policy:". Have not thoroughly validated the others.

## Describe the problem

Example JSON payload below "The JSON below is an example of the request body parameters you need to add a custom build policy:" is incorrect. Easy to fix if you copy paste it to a code editor.
Problem is in payload.**rule.children**

## Suggested fix
Change to:
payload =  {
        "cloudType": "aws",
        "complianceMetadata": [],
        "description": "",
        "labels": [],
        "name": "demo",
        "policySubTypes": [
            "build"
        ],
        "policyType": "config",
        "recommendation": "",
        "rule": {
                "children": [{
                    "criteria": "{\"category\":\"Storage\",\"resourceTypes\":[\"aws_s3_bucket\"],\"conditionQuery\":{\"attribute\":\"acl\",\"operator\":\"not_equals\",\"value\":\"log-delivery-write\",\"cond_type\":\"attribute\"}}",
                    "type": "build",
                    "recommendation": ""
                    }
                ],
            "name": "demo",
            "parameters": {
                "savedSearch": "false",
                "withIac": "true"
            },
            "type": "Config"
        },
        "severity": "low"
    }

**Comment by jrdevore** [comment]
Closed in #705 ! Thank you for submitting the issue.
