### ISSUE TITLE
Issue/Help with "Get Top Impacting Vulnerabilities"

### ISSUE THREAD

**Issue by t3xtm0d3** [PaloAltoNetworks/pan.dev#665]
## Documentation link

https://pan.dev/prisma-cloud/api/cspm/top-prioritised-vulnerability/
Parameter: top (integer)

## Describe the problem

The parameter "top" seems to ignore the value if it is greater than 10. 

## Suggested fix

If this is the feature, it should state the maximum number of the parameter to be 10.
If not, the results from the API should have been matched with the number in the parameter.

**Comment by AbiMano4688** [comment]
Thank you for the feedback.
Included possible values for the top parameter.
PR: https://github.com/PaloAltoNetworks/pan.dev/pull/677
